
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shailendrabrain/library-config
          default-label: newconfig
          username: server
          password: server